### ISSUE TITLE
Sample config is incorrect

### ISSUE THREAD

**Issue by jonwaland** [LRvdLinden/UptimeRobot-HA-Card#2]
Hi - the sample config you have is incorrect there are various extra spaces that shouldn't be there (alias: onwards). Plus the vertical stack is only needed if using multiple instances.

working example:
```
type: 'custom:uptime-card'
entity: binary_sensor.homeassistant
icon: 'fas:safari'
name: HomeAssistant
hours_to_show: 72
status_adaptive_color: true
average_text: '% uptime'
alias:
  ok: Online
  ko: Offline
color:
  icon: white
  ok: '#45C669'
  ko: '#C6B145'
  half: '#C66445'
  none: '#C9C9C9'
  title: white
show:
  header: true
  title: true
  icon: true
  footer: true
  status: true
  timeline: true
  average: true
tooltip:
  animation: true
title_adaptive_color: true
icon_adaptive_color: true
tooltip_adaptive_color: true
bar: {}
tap_action:
  action: more-info
alignment:
  header: spaced
  status: spaced
```
